spring.application.name=git_test

spring.datasource.url=jdbc:mysql://localhost:3306/db_sports?useSSL=false&&allowPublicKeyRetrieval=true&&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username = root
spring.datasource.password = 184703

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true